<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';

try {
    $release = latest_release();
    $downloads = (int) db()->query('SELECT COUNT(*) FROM download_events')->fetchColumn();
    $active = (int) db()->query("SELECT COUNT(*) FROM installations WHERE last_seen_at >= (NOW() - INTERVAL 30 DAY)")->fetchColumn();
} catch (Throwable $error) {
    $release = null; $downloads = 0; $active = 0;
}

render_head('تحميل تطبيق محاضراتي');
?>
<header class="wrap site-header"><a class="brand" href="./"><span class="brand-mark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15.5A2.5 2.5 0 0 0 17.5 16H4z"/><path d="M4 5.5A2.5 2.5 0 0 1 6.5 8H20"/><path d="M8 12h7M8 15h5"/></svg></span><span class="brand-word">محاضراتي<small>MO7ADARATY</small></span></a><nav class="top-nav"><a href="#features">المزايا</a><a href="#install">التثبيت</a><a href="admin/login.php" class="admin-link">لوحة الإدارة</a></nav></header>
<main>
  <section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow"><span class="pulse"></span> الإصدار الرسمي لأندرويد</span><h1>رفيقك الدراسي<br><span>في تطبيق واحد متكامل</span></h1><p class="lead">نظّم محاضراتك في مجلدات بلا حدود، احتفظ بملفاتك على جهازك، واقرأ وشغّل موادك الدراسية بسهولة حتى من دون اتصال.</p><div class="hero-actions"><a class="button" href="#download">تنزيل التطبيق <span aria-hidden="true">←</span></a><a class="button alt" href="#features">استكشف المزايا</a></div><p class="hero-note"><strong>خصوصيتك أولاً.</strong> تبقى ملفاتك داخل مساحة التطبيق على جهازك.</p></div><div class="release-orb"><article class="release-card"><div class="release-top"><span class="release-label">أحدث إصدار متاح</span><span class="release-badge">ANDROID APK</span></div><div class="mock-folders"><div class="folder three"></div><div class="folder two"></div><div class="folder one"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 3h9l5 5v13H5z"/><path d="M14 3v6h6M8 14h8M8 17h6"/></svg></div></div><h2 class="release-version"><?= $release ? 'v' . e($release['version_name']) : 'قريباً' ?><small><?= $release ? 'بناء ' . (int)$release['version_code'] : 'الإصدار الأول' ?></small></h2><p class="release-copy"><?= $release ? e(mb_strimwidth($release['changelog'],0,130,'…')) : 'يجري تجهيز رابط التنزيل الرسمي.' ?></p><div class="release-meta"><span class="chip"><b>محلي</b> بدون إنترنت</span><span class="chip"><b>PDF</b> وصور</span><span class="chip"><b>RTL</b> عربية</span></div></article></div></div></section>
  <section class="stat-strip"><div class="wrap stats"><div class="stat"><strong><?= number_format($downloads) ?></strong><span>نقرة تنزيل مسجلة</span></div><div class="stat"><strong><?= number_format($active) ?></strong><span>أجهزة نشطة تقديرياً</span></div><div class="stat"><strong>Android 7+</strong><span>الحد الأدنى للتشغيل</span></div></div></section>
  <section id="features" class="section"><div class="wrap"><span class="section-kicker">مصمم لحياتك الدراسية</span><h2 class="section-title">مكتبتك الأكاديمية،<br>مرتبة دائماً وفي متناولك.</h2><p class="section-text">كل التفاصيل الأساسية التي تحتاجها لإدارة المذكرات والمحاضرات والمستندات، داخل تجربة عربية هادئة وواضحة.</p><div class="feature-grid"><article class="feature"><span class="icon-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 6.5h6l2 2h10v10.5A2 2 0 0 1 19 21H5a2 2 0 0 1-2-2z"/><path d="M3 6.5A2.5 2.5 0 0 1 5.5 4H10l1 2.5"/></svg></span><h3>مجلدات بلا حدود</h3><p>أنشئ أقساماً ومجلدات فرعية، وخصص اللون والأيقونة لكل مقرر.</p></article><article class="feature"><span class="icon-box mint"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg></span><h3>قراءة داخلية</h3><p>شاهد الصور وملفات PDF مباشرة، وشغّل الوسائط المتوافقة داخل التطبيق.</p></article><article class="feature"><span class="icon-box orange"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="11" width="12" height="10" rx="2"/><path d="m15 14 5-3v10l-5-3zM7 7l2-2 2 2"/></svg></span><h3>مشاركة مرنة</h3><p>شارك ملفاً أو عدة ملفات كما هي، وشارك المجلد كاملاً كملف مضغوط.</p></article></div></div></section>
  <section id="download" class="section" style="padding-top:0"><div class="wrap"><div class="download-zone"><div class="download-head"><div><span class="section-kicker">تنزيل موثوق</span><h2>اختر مصدر التنزيل المناسب لك</h2></div><p>كل المصادر تؤدي إلى الإصدار نفسه. تُسجل نقرة التنزيل لتحسين الخدمة، ولا يحفظ الموقع ملف APK محلياً.</p></div><div class="mirrors"><?php if ($release): foreach (['github' => ['GitHub','GitHub Releases','github_url'], 'googleDrive' => ['G','Google Drive','google_drive_url'], 'mediaFire' => ['MF','MediaFire','mediafire_url']] as $key => [$mark,$label,$urlKey]): if (empty($release[$urlKey])) continue; ?><div class="mirror"><div class="mirror-left"><span class="mirror-logo"><?= e($mark) ?></span><div><div class="mirror-title"><?= e($label) ?></div><div class="mirror-desc"><?= $key === 'github' ? 'المصدر الأساسي المؤرشف' : 'مرآة تنزيل بديلة' ?></div></div></div><a class="button alt" href="download.php?mirror=<?= e($key) ?>">تنزيل</a></div><?php endforeach; else: ?><p>لا توجد روابط تنزيل منشورة بعد.</p><?php endif; ?></div></div></div></section>
  <section id="install" class="section" style="padding-top:0"><div class="wrap"><span class="section-kicker">3 خطوات فقط</span><h2 class="section-title">ثبّت التطبيق وابدأ تنظيم موادك.</h2><div class="install-grid"><article class="step"><span class="step-no">01</span><h3>نزّل ملف APK</h3><p>اضغط زر التنزيل واختر المصدر الذي يناسبك.</p></article><article class="step"><span class="step-no">02</span><h3>اسمح بالتثبيت</h3><p>عند طلب Android، اسمح لتطبيق التنزيل بتثبيت هذا الملف.</p></article><article class="step"><span class="step-no">03</span><h3>افتح محاضراتي</h3><p>أنشئ مجلدك الأول واستورد ملفاتك الدراسية إليه.</p></article></div></div></section>
</main><footer class="footer"><div class="wrap footer-inner"><span>© <?= date('Y') ?> محاضراتي · رفيقك الدراسي المحلي</span><span><a href="privacy.php">الخصوصية</a> · <a href="admin/login.php">الإدارة</a></span></div></footer>
<?php render_foot(); ?>
